### ISSUE TITLE
Best way to translate the form

### ISSUE THREAD

**Issue by Floriferous** [Zetoff/accounts-material-ui#22]
I'd like to use this awesome add-on on a french (and later internationalized) website, is there a simple way of redefining all used texts/labels and error messages?

**Comment by PolGuixe** [comment]
@Floriferous currently we are using: https://github.com/softwarerero/meteor-accounts-t9n

In order to change the language you need to set the locale. You need to set the locale.

```js
import {T9n} from 'meteor/softwarerero:accounts-t9n';

Meteor.startup(() => {
  // locale or language can be hardcoded or obtained from 
  // the browser or from different variable on your project
   T9n.setLanguage(DEFAULT_LOCALE); // For the std:accounts-ui package
}
```

I hope it helps.
